[package]
name    = "nalgebra-lapack"
version = "0.14.0"
authors = [ "Sébastien Crozet <developer@crozet.re>", "Andrew Straw <strawman@astraw.com>" ]

description   = "Linear algebra library with transformations and satically-sized or dynamically-sized matrices."
documentation = "https://nalgebra.org/doc/nalgebra/index.html"
homepage      = "https://nalgebra.org"
repository    = "https://github.com/rustsim/nalgebra"
readme        = "README.md"
keywords      = [ "linear", "algebra", "matrix", "vector" ]
license       = "Apache-2.0"
edition       = "2018"

[features]
serde-serialize = [ "serde", "serde_derive" ]

# For BLAS/LAPACK
default    = ["openblas"]
openblas   = ["lapack-src/openblas"]
netlib     = ["lapack-src/netlib"]
accelerate = ["lapack-src/accelerate"]
intel-mkl  = ["lapack-src/intel-mkl"]

[dependencies]
nalgebra      = { version = "0.22" } # , path = ".." }
num-traits    = "0.2"
num-complex   = { version = "0.2", default-features = false }
simba         = "0.2"
serde         = { version = "1.0", optional = true }
serde_derive  = { version = "1.0", optional = true }
lapack        = { version = "0.16", default-features = false }
lapack-src    = { version = "0.5", default-features = false }
# clippy = "*"

[dev-dependencies]
nalgebra   = { version = "0.22", features = [ "arbitrary" ] } # path = ".." }
quickcheck = "0.9"
approx     = "0.3"
rand       = "0.7"
